# Generated by Django 5.2.7 on 2025-11-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('reference_text', models.TextField(blank=True, help_text='Texto completo de la referencia (APA o similar).')),
                ('section', models.CharField(blank=True, choices=[('home', 'Home'), ('que-es-ia', 'Qué es la IA'), ('como-funciona-un-llm', 'Cómo funciona un LLM'), ('entorno-academico', 'Entorno académico'), ('pensamiento-critico', 'Pensamiento crítico')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bibliografía',
                'ordering': ['section', 'author'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('type', models.CharField(choices=[('feature-card', 'Feature Card'), ('simple-text-block', 'Simple Text Block')], max_length=30)),
                ('section', models.CharField(choices=[('home', 'Home'), ('que-es-ia', 'Qué es la IA'), ('como-funciona-un-llm', 'Cómo funciona un LLM'), ('entorno-academico', 'Entorno académico'), ('pensamiento-critico', 'Pensamiento crítico')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
