# Generated by Django 5.2.7 on 2025-11-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Texto alternativo para la imagen (usado en accesibilidad y SEO).', max_length=255),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='author',
            field=models.CharField(blank=True, help_text='Autor del articulo', max_length=255),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link del articulo original (una dirección tipo https://scholar.google.com/)'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='title',
            field=models.CharField(help_text='Titulo del articulo', max_length=255),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='year',
            field=models.CharField(blank=True, help_text='Año de publicación del articulo', max_length=10),
        ),
    ]
